#!/usr/bin/env sh
cd ../pymc/PyMC
export PYTHONPATH="`pwd`:$PYTHONPATH"
cd ..
#export PYTHONPATH="`pwd`/build/lib.linux-x86_64-2.4/PyMC/flib.so:$PYTHONPATH"
#export PYTHONPATH="`pwd`/build/lib.linux-x86_64-2.4:$PYTHONPATH"
export PYTHONPATH="`pwd`/build/lib.linux-i686-2.4:$PYTHONPATH"
cd ../chemev
