#!/usr/bin/env sh
cd ../pymc/PyMC
export PYTHONPATH="`pwd`:$PYTHONPATH"
cd ..
#this works for goods15
export PYTHONPATH="`pwd`/build/lib.linux-x86_64-2.4:$PYTHONPATH"
#this works for linux
export PYTHONPATH="`pwd`/build/lib.linux-i686-2.4:$PYTHONPATH"
#we can have both in the search path, it's not a problem
cd ../chemev
